# Name
name: pyjsi-env

# Channels to look for any specific libraries
channels:
  - local

# App dependencies to be installed
dependencies:
  - python=3.10
  - pip
  - android-python * py310*
  - android-pybind11
